### PR TITLE
fix most PEP8 issues and run flake8 as part of CI

### PR DESCRIPTION
**Pull request by jtauber**
See #44 for earlier discussion.

I've fixed all flake8 violations except: W191 (tabs), E266 (more than one `#` starting a comment) and E501 (lines over 80 characters).

As mentioned elsewhere, ignoring W191 doesn't help make indentation consistent, it just ignores warnings about tabs. So it cannot detect files using spaces (as that's the normal Python convention). There are actually some files in the repo that use spaces. I did not change these. A couple of files mixed tabs and spaces and I changed those to use tabs.

I've also hooked up flake8 as part of Travis CI.

I excluded `sgflib` from the flake8 run in Travis CI and did not make any changes to the files there.

### CODE REVIEW

**Comment by wrongu** [comment]
Looks great! Do you mind if we wait until after the first milestone to merge this? We have a few other branches that have diverged from develop and should be merged by Monday. Fixing formatting in a single merged branch seems easier than dealing with merge conflicts in all of them.

**Comment by jtauber** [comment]
Sure. Give me a heads up and I'll re-do it.

**Comment by jtauber** [comment]
@wrongu let me know if you want me to redo this now

**Comment by wrongu** [comment]
That would be great, thanks!

**Comment by jtauber** [comment]
I'll start again and issue a separate PR.

**Pull request closed without merging**
